* About
This script does not show how to partition the disks, as that varies
between different computers and user preferences

* What =partition-disks= does

* What =gentoo-installer= does
The script performs a minimal install of Gentoo
Linux on BTRFS file system, with System-D and GenKernel automatically
without any user input once it is executed.

I choose not to use the latest Stage 3 tarball and kernel versions, as
these have been tested and have no errors. Using the latest versions has
the potential of creating an extra point of failure during the
installation process.

Similarly, Genkernel is used to both avoid manually configuring the
kernel and to narror the points of failure when booting in the system
for the first time. Once the system has been booted successfully,
Genkernel can be replaced with a customized kernel configuration.

This does not partition or format the disks, that is left to the user or
done with the script "partition-disks.sh"

* How to use the scripts
Since there is no user input required, all customizations to commands
are set as veriables at the beginnig of the script. All customizations
to files that would be configured with a text editor of choice would be
done on template files found in this project root directory.
